-- Cyber Torque admin schema

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_name varchar(100) not null unique,
  role varchar(30) not null default 'user',
  password varchar(255) not null
);

alter table public.users enable row level security;

drop policy if exists "Public users can be read by the admin API" on public.users;
create policy "Public users can be read by the admin API"
  on public.users
  for select
  to anon, authenticated
  using (true);

insert into public.users (user_name, role, password)
values ('admin', 'admin', 'admin')
on conflict (user_name) do nothing;

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  slug varchar(160) not null unique,
  brand varchar(100) not null,
  name varchar(160) not null,
  model varchar(160) not null,
  variant varchar(100),
  category varchar(100) not null,
  image text not null,
  hero_image text not null,
  frames text[] not null default '{}',
  horsepower varchar(50) not null,
  acceleration varchar(50) not null,
  engine varchar(100) not null,
  seats varchar(20) not null,
  price varchar(80) not null,
  base_price varchar(80) not null,
  year integer not null default extract(year from now()),
  description text not null default '',
  published boolean not null default true
);

alter table public.vehicles enable row level security;

drop policy if exists "Published vehicles are publicly readable" on public.vehicles;
create policy "Published vehicles are publicly readable"
  on public.vehicles
  for select
  to anon, authenticated
  using (published = true);

drop policy if exists "Admin API can read all vehicles" on public.vehicles;
create policy "Admin API can read all vehicles"
  on public.vehicles
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Admin API can update vehicles" on public.vehicles;
create policy "Admin API can update vehicles"
  on public.vehicles
  for update
  to anon, authenticated
  using (true)
  with check (true);

create index if not exists vehicles_brand_idx on public.vehicles (brand);
create index if not exists vehicles_category_idx on public.vehicles (category);
create index if not exists vehicles_published_idx on public.vehicles (published);