-- Cyber Torque admin schema

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_name varchar(100) not null unique,
  email varchar(255),
  role varchar(30) not null default 'employee' check (role in ('admin', 'employee')),
  password varchar(255) not null
);

alter table public.users add column if not exists email varchar(255);
update public.users set role = 'employee' where role not in ('admin', 'employee');
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check check (role in ('admin', 'employee'));

alter table public.users enable row level security;

-- Revoke open public read access on users.
-- Only the service_role (used by server-side admin operations) has access to user credentials.
drop policy if exists "Public users can be read by the admin API" on public.users;
drop policy if exists "Service role has full access to users" on public.users;
create policy "Service role has full access to users"
  on public.users
  for all
  to service_role
  using (true)
  with check (true);

-- Optional secure RPC function to look up a user by username without exposing the entire table
create or replace function public.get_auth_user(p_username text)
returns table (id bigint, user_name varchar, role varchar, password varchar)
language sql
security definer
set search_path = public
as $$
  select id, user_name, role, password
  from public.users
  where user_name = p_username
  limit 1;
$$;

-- Seed initial admin user with bcrypt-hashed password for 'admin'
insert into public.users (user_name, role, password)
values ('admin', 'admin', '$2b$10$ImrVkcbU6q3CtICV.3pR3eks.w7VdQp7AaBr692FW7LV01XcKHcUm')
on conflict (user_name) do nothing;

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  slug varchar(160) not null unique,
  brand varchar(100) not null,
  name varchar(160) not null,
  model varchar(160) not null,
  variant varchar(100),
  category varchar(100) not null,
  image text not null,
  hero_image text not null,
  frames text[] not null default '{}',
  horsepower varchar(50) not null,
  acceleration varchar(50) not null,
  engine varchar(100) not null,
  seats varchar(20) not null,
  price varchar(80) not null,
  base_price varchar(80) not null,
  year integer not null default extract(year from now()),
  description text not null default '',
  published boolean not null default true
);

alter table public.vehicles enable row level security;

-- Published vehicles are publicly readable by anyone
drop policy if exists "Published vehicles are publicly readable" on public.vehicles;
create policy "Published vehicles are publicly readable"
  on public.vehicles
  for select
  to anon, authenticated
  using (published = true);

-- Remove insecure public update policy. Admin API uses service_role for modifications.
drop policy if exists "Admin API can update vehicles" on public.vehicles;
drop policy if exists "Admin API can read all vehicles" on public.vehicles;
drop policy if exists "Service role has full access to vehicles" on public.vehicles;

create policy "Service role has full access to vehicles"
  on public.vehicles
  for all
  to service_role
  using (true)
  with check (true);

create index if not exists vehicles_brand_idx on public.vehicles (brand);
create index if not exists vehicles_category_idx on public.vehicles (category);
create index if not exists vehicles_published_idx on public.vehicles (published);

create table if not exists public.vehicle_tracking (
  id bigint generated by default as identity primary key,
  tracking_id varchar(40) not null unique,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  status varchar(40) not null default 'Order received' check (status in ('Order received', 'Preparing vehicle', 'In transit', 'Ready for collection', 'Completed')),
  location varchar(160) not null default '',
  estimated_delivery date,
  notes text not null default '',
  updated_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.vehicle_tracking enable row level security;
drop policy if exists "Public tracking lookup" on public.vehicle_tracking;
create policy "Public tracking lookup" on public.vehicle_tracking
  for select to anon, authenticated using (true);
drop policy if exists "Service role has full access to tracking" on public.vehicle_tracking;
create policy "Service role has full access to tracking" on public.vehicle_tracking
  for all to service_role using (true) with check (true);

create index if not exists vehicle_tracking_vehicle_idx on public.vehicle_tracking (vehicle_id);
create index if not exists vehicle_tracking_status_idx on public.vehicle_tracking (status);